title: Dichter bij De Vader
description: >-
  Wil je God beter leren kennen maar weet je niet goed hoe?
  Met behulp van korte overdenkingen help ik je antwoord te vinden op herkenbare vragen.
url: "HarmPrins.nl"

# Personal info
author: Harm Prins
email: harmp98@gmail.com
github_username:  HarmP
linkedin_username: HarmP98

# Site settings
permalink: /:year-:month-:day/:title
show_excerpts: true
header_pages:
  - categories/categories.markdown
  - about.markdown

# Build settings
theme: minima
plugins:
  - jekyll-feed
