title: Dichter bij De Vader
description: >-
  Wil je God beter leren kennen maar weet je niet goed hoe?
  Met behulp van een korte overdenking en gebed help ik je antwoord te vinden op herkenbare vragen.
url: "HarmPrins.nl"

# Personal info
author: Harm Prins
email: harmp98@gmail.com
github_username:  Harmp
linkedin_username: harmp98

# Build settings
permalink: /:year-:month-:day/:title
show_excerpts: true
theme: minima
plugins:
  - jekyll-feed